
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.212:3306/db_videoyi_test?autoReconnect=true&characterEncoding=UTF8
    username: root
    password: Yp@Mb#691
    driver-class-name: com.mysql.cj.jdbc.Driver


